### ISSUE TITLE
Replace Gradle update checker

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Android#2525]
The current update checker, https://github.com/obfusk/gradle-update-action, has sadly stopped working and is no longer maintained.

Need to replace it with the official upstream Gradle version update checker (or dependabot, if that supports it)

**Comment by JessieG-TY** [comment]
This will scan build.gradle.kts and every module, automatically detects if Gradle is out of date every week.
```
version: 2
updates: 
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly" 
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"

**Comment by TheLastProject** [comment]
As stated in #2529, we already have dependabot running for years, but it only seems to update dependencies, not gradle itself, which is why we also had https://github.com/CatimaLoyalty/Android/blob/e297620ea24b51ebfb739aad2b00edf3f9905ff1/.github/workflows/gradle-update.yml for years to make PRs like https://github.com/CatimaLoyalty/Android/pull/2474 but which stopped working and is no longer maintained.

I'm pretty sure the Gradle team has some official Github Action for this, which is probably the safest way.

**Comment by PrathameshBhagat** [comment]
### Alternative Solution : https://github.com/gradle-update/update-gradle-wrapper-action
(Probably official one)

A bit about me : I have built multiple Java/Android apps (personal), but I'm not very familiar with Gradle, I have used it in those apps and have configured a few Github Actions in my other personal projects.

I found this fix via LLM, and Google says it's official **but I didn't found links redirecting to microsoft/GitHub**, it's used by 2K + users. (Haven't used it myself yet, just pointing to a probable solution to this issue)


## Usage
#### 1) Create a new dedicated workflow file:

.github/workflows/update-gradle-wrapper.yml

#### 2) Paste this configuration:
```
name: Update Gradle Wrapper

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v2
``` 
  
  
P.S. : I'm currently looking to work on migrating your java classes to kotlin/Compose. I might add this action to that pull request if you like or create a separate one with this action.
